repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]
        
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true