repos:
-   repo: local
    hooks:
    -   id: ruff_check
        name: ruff_check
        entry: ruff check --fix
        language: system
        types: [python]

    -   id: ruff_format
        name: ruff_format
        entry: ruff format
        language: system
        types: [python]
        
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true