AWSTemplateFormatVersion: '2010-09-09'
Description: 'Health Tracking Data Sync Lambda Function'

Parameters:
  GoogleTokenSecretName:
    Type: String
    Default: health-tracking/google-token
    Description: Name of the secret in Secrets Manager that contains Google OAuth token

  FitbitTokenSecretName:
    Type: String
    Default: health-tracking/fitbit-token
    Description: Name of the secret in Secrets Manager that contains Fitbit OAuth token
    
  FitbitClientIdSecretName:
    Type: String
    Default: health-tracking/fitbit-client-id
    Description: Name of the secret in Secrets Manager that contains Fitbit Client ID
    
  FitbitClientSecretSecretName:
    Type: String
    Default: health-tracking/fitbit-client-secret
    Description: Name of the secret in Secrets Manager that contains Fitbit Client Secret

  ECRRepositoryUri:
    Type: String
    Description: URI of the ECR repository where the Docker image is stored

  ImageTag:
    Type: String
    Default: latest
    Description: Docker image tag to deploy

  SpreadsheetId:
    Type: String
    Description: Google Sheets spreadsheet ID

  SleepSheetName:
    Type: String
    Default: Sleep
    Description: Name of the sheet for sleep data

  HeartRateSheetName:
    Type: String
    Default: HeartRate
    Description: Name of the sheet for heart rate data

  SyncScheduleExpression:
    Type: String
    Default: cron(0 14-17 * * ? *)  # Run hourly from 7:00 AM to 10:00 AM PT (14:00-17:00 UTC)
    Description: Schedule expression for sync (CloudWatch Events cron syntax)

  NotificationEmail:
    Type: String
    Default: self@brendanlong.com
    Description: Email address for failure notifications

Resources:
  GoogleTokenSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Ref GoogleTokenSecretName
      Description: "Google OAuth token for health tracking sync"
  
  FitbitTokenSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Ref FitbitTokenSecretName
      Description: "Fitbit OAuth token for health tracking sync"
      
  FitbitClientIdSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Ref FitbitClientIdSecretName
      Description: "Fitbit Client ID for health tracking sync"
      
  FitbitClientSecretSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Ref FitbitClientSecretSecretName
      Description: "Fitbit Client Secret for health tracking sync"

  # IAM Role for Lambda Function
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: 
                  - !Ref GoogleTokenSecret
                  - !Ref FitbitTokenSecret
                  - !Ref FitbitClientIdSecret
                  - !Ref FitbitClientSecretSecret

  # Lambda Function for Sleep Data Sync
  SleepSyncLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: health-tracking-sleep-sync
      PackageType: Image
      Code:
        ImageUri: !Sub ${ECRRepositoryUri}:${ImageTag}
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300  # 5 minutes should be enough for syncing
      MemorySize: 512  # 512 MB of memory
      Environment:
        Variables:
          GOOGLE_TOKEN_SECRET_NAME: !Ref GoogleTokenSecretName
          FITBIT_TOKEN_SECRET_NAME: !Ref FitbitTokenSecretName
          FITBIT_CLIENT_ID_SECRET_NAME: !Ref FitbitClientIdSecretName
          FITBIT_CLIENT_SECRET_SECRET_NAME: !Ref FitbitClientSecretSecretName
          SPREADSHEET_ID: !Ref SpreadsheetId
          SHEET_NAME: !Ref SleepSheetName
          SYNC_TYPE: sleep

  # Lambda Function for Heart Rate Data Sync
  HeartRateSyncLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: health-tracking-heartrate-sync
      PackageType: Image
      Code:
        ImageUri: !Sub ${ECRRepositoryUri}:${ImageTag}
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 300  # 5 minutes should be enough for syncing
      MemorySize: 512  # 512 MB of memory
      Environment:
        Variables:
          GOOGLE_TOKEN_SECRET_NAME: !Ref GoogleTokenSecretName
          FITBIT_TOKEN_SECRET_NAME: !Ref FitbitTokenSecretName
          FITBIT_CLIENT_ID_SECRET_NAME: !Ref FitbitClientIdSecretName
          FITBIT_CLIENT_SECRET_SECRET_NAME: !Ref FitbitClientSecretSecretName
          SPREADSHEET_ID: !Ref SpreadsheetId
          SHEET_NAME: !Ref HeartRateSheetName
          SYNC_TYPE: heart-rate

  # CloudWatch Event Rule for Sleep Data Sync
  SleepSyncEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Daily trigger for sleep data sync
      ScheduleExpression: !Ref SyncScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt SleepSyncLambdaFunction.Arn
          Id: sleep-sync-target

  # CloudWatch Event Rule for Heart Rate Data Sync
  HeartRateSyncEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Daily trigger for heart rate data sync
      ScheduleExpression: !Ref SyncScheduleExpression
      State: ENABLED
      Targets:
        - Arn: !GetAtt HeartRateSyncLambdaFunction.Arn
          Id: heartrate-sync-target

  # Permissions for CloudWatch Events to invoke Lambda
  SleepSyncPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SleepSyncLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SleepSyncEventRule.Arn

  HeartRateSyncPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref HeartRateSyncLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt HeartRateSyncEventRule.Arn

  # SNS Topic for Failure Notifications
  FailureNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: health-tracking-sync-failures
      DisplayName: Health Tracking Sync Failures
      Subscription:
        - Protocol: email
          Endpoint: !Ref NotificationEmail

  # CloudWatch Alarms for Lambda Failures
  SleepSyncFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: health-tracking-sleep-sync-failures
      AlarmDescription: Alert when sleep sync lambda fails
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref SleepSyncLambdaFunction
      AlarmActions:
        - !Ref FailureNotificationTopic
      TreatMissingData: notBreaching

  HeartRateSyncFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: health-tracking-heartrate-sync-failures
      AlarmDescription: Alert when heart rate sync lambda fails
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 86400  # 24 hours
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref HeartRateSyncLambdaFunction
      AlarmActions:
        - !Ref FailureNotificationTopic
      TreatMissingData: notBreaching

Outputs:
  SleepSyncLambdaArn:
    Description: ARN of the Sleep Sync Lambda function
    Value: !GetAtt SleepSyncLambdaFunction.Arn

  HeartRateSyncLambdaArn:
    Description: ARN of the Heart Rate Sync Lambda function
    Value: !GetAtt HeartRateSyncLambdaFunction.Arn