AWSTemplateFormatVersion: '2010-09-09'
Description: 'Import template for existing Secret'

Resources:
  GoogleCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: health-tracking/google-credentials
      Description: "Google API credentials for health tracking sync"
